// ── @shared ────────────────────────────────────────────────────────────────
import type { FileStamp } from '@shared'

// ── @i18n ──────────────────────────────────────────────────────────────────
import { t } from '@i18n/active'

// ── @services ──────────────────────────────────────────────────────────────
import { toast } from '@services'

// ── @store ─────────────────────────────────────────────────────────────────
import { contentChanged, dispatch, documentSaved, externalStateChanged, getState, isDirty, selectActiveDocument, selectDocumentByPath } from '@store'

// ── @features ──────────────────────────────────────────────────────────────
import { reloadFromDisk } from './document-save'

/**
 * Reacting to a document changing underneath us.
 */
/* ────────────────────────────────────────────────────────────────────────────
 * External change handling
 * ─────────────────────────────────────────────────────────────────────────── */

export async function handleExternalChange(path: string, stamp: FileStamp): Promise<void> {
  const document = selectDocumentByPath(getState(), path)
  if (!document) return

  // Our own save produced this event.
  if (document.stamp && document.stamp.hash === stamp.hash) return

  if (!isDirty(document)) {
    // Nothing to lose: silently adopt the newer content, which is what a user
    // expects when a file is regenerated by another tool.
    await reloadFromDisk(document.id)
    toast.info(t('notifications.reloaded'), t('notifications.reloadedDetail', { name: document.title }))
    return
  }

  dispatch(externalStateChanged({ id: document.id, external: 'changed', stamp }))
}

export function handleExternalRemoval(path: string): void {
  const document = selectDocumentByPath(getState(), path)
  if (!document) return
  dispatch(externalStateChanged({ id: document.id, external: 'removed', stamp: null }))
}

/** The banner's "Reload" action. */
export async function acceptExternalChange(id: string): Promise<void> {
  await reloadFromDisk(id)
}

/** The banner's "Keep my version" action. */
export function keepLocalVersion(id: string): void {
  const document = getState().documents.entities[id]
  if (!document) return

  // Adopting the external stamp means the next save is a clean, intentional
  // overwrite rather than another conflict prompt.
  if (document.externalStamp && document.path) {
    dispatch(
      documentSaved({
        id,
        path: document.path,
        stamp: document.externalStamp,
        content: document.savedContent
      })
    )
    dispatch(contentChanged({ id, content: document.content }))
  }

  dispatch(externalStateChanged({ id, external: 'none', stamp: null }))
}

export { selectActiveDocument }

